title: Husni Kamal
description: Simple Blog and Just Curat Coret!

url: http://pelung.github.com/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: pelung
   twitter: pelung
   facebook: pelung
   email: pelungdesigns@gmail.com

google_analytics: 
